# Generated by Django 5.1.5 on 2025-01-24 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('spine', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1870)])),
                ('letterboxd', models.URLField()),
                ('countries', models.ManyToManyField(related_name='films', to='common.country')),
                ('directors', models.ManyToManyField(related_name='films', to='directors.director')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
