# Generated by Django 5.1.5 on 2025-01-17 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("directors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                ("cc_id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("spine", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, validators=[django.core.validators.MinValueValidator(1870)]
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("AO", "Angola"),
                            ("AR", "Argentina"),
                            ("AU", "Australia"),
                            ("AT", "Austria"),
                            ("BD", "Bangladesh"),
                            ("BE", "Belgium"),
                            ("BR", "Brazil"),
                            ("CM", "Cameroon"),
                            ("CA", "Canada"),
                            ("CN", "China"),
                            ("CU", "Cuba"),
                            ("CZ", "Czechoslovakia"),
                            ("DK", "Denmark"),
                            ("ET", "Ethiopia"),
                            ("FI", "Finland"),
                            ("FR", "France"),
                            ("DE", "Germany"),
                            ("GR", "Greece"),
                            ("GT", "Guatemala"),
                            ("HK", "Hong Kong"),
                            ("HU", "Hungary"),
                            ("IS", "Iceland"),
                            ("IN", "India"),
                            ("ID", "Indonesia"),
                            ("IR", "Iran"),
                            ("IE", "Ireland"),
                            ("IT", "Italy"),
                            ("JP", "Japan"),
                            ("KZ", "Kazakhstan"),
                            ("LS", "Lesotho"),
                            ("MX", "Mexico"),
                            ("MA", "Morocco"),
                            ("NZ", "New Zealand"),
                            ("NG", "Nigeria"),
                            ("NO", "Norway"),
                            ("PH", "Philippines"),
                            ("PL", "Poland"),
                            ("PT", "Portugal"),
                            ("MK", "Republic of Macedonia"),
                            ("RO", "Romania"),
                            ("SN", "Senegal"),
                            ("KR", "South Korea"),
                            ("SU", "Soviet Union"),
                            ("ES", "Spain"),
                            ("SE", "Sweden"),
                            ("CH", "Switzerland"),
                            ("TW", "Taiwan"),
                            ("TH", "Thailand"),
                            ("TR", "Turkey"),
                            ("UA", "Ukraine"),
                            ("GB", "United Kingdom"),
                            ("US", "United States"),
                            ("WG", "West Germany"),
                            ("YU", "Yugoslavia"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("letterboxd", models.URLField()),
                ("directors", models.ManyToManyField(related_name="films", to="directors.director")),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
