# Generated by Django 5.1.5 on 2025-01-17 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("year", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1870)])),
                ("letterboxd", models.URLField()),
            ],
        ),
    ]
