# Generated by Django 5.1.5 on 2025-01-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(related_name='films', to='directors.director'),
        ),
    ]
