# Generated by Django 5.1.5 on 2025-01-25 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_venue'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='films.film')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='common.venue')),
            ],
            options={
                'verbose_name': 'Session',
                'ordering': ['datetime'],
            },
        ),
    ]
