# Generated by Django 5.1.5 on 2025-01-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0002_filmsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="cc_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
