# Generated by Django 5.1.5 on 2025-01-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_directors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title']},
        ),
    ]
