# Generated by Django 5.1.5 on 2025-01-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='spine',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
