# Generated by Django 5.1.5 on 2025-01-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_genre'),
        ('films', '0005_film_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='films', to='common.genre'),
        ),
    ]
