# Generated by Django 5.1.5 on 2025-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0005_film_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="cc_id",
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
