# Generated by Django 5.1.5 on 2025-01-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_keyword'),
        ('films', '0006_film_runtime_alter_film_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='films', to='common.keyword'),
        ),
    ]
