# Generated by Django 5.1.5 on 2025-01-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_gender'),
        ('films', '0007_film_keywords'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmsession',
            unique_together={('film', 'venue', 'datetime')},
        ),
    ]
