# Generated by Django 5.1.5 on 2025-01-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_film_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='spine',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
