# Generated by Django 5.1.5 on 2025-01-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_film_spine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(choices=[('AO', 'Angola'), ('AR', 'Argentina'), ('AU', 'Australia'), ('AT', 'Austria'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BR', 'Brazil'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('CN', 'China'), ('CU', 'Cuba'), ('CZ', 'Czechoslovakia'), ('DK', 'Denmark'), ('ET', 'Ethiopia'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('GR', 'Greece'), ('GT', 'Guatemala'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IE', 'Ireland'), ('IT', 'Italy'), ('JP', 'Japan'), ('KZ', 'Kazakhstan'), ('LS', 'Lesotho'), ('MX', 'Mexico'), ('MA', 'Morocco'), ('NZ', 'New Zealand'), ('NG', 'Nigeria'), ('NO', 'Norway'), ('PH', 'Philippines'), ('PL', 'Poland'), ('PT', 'Portugal'), ('MK', 'Republic of Macedonia'), ('RO', 'Romania'), ('SN', 'Senegal'), ('KR', 'South Korea'), ('SU', 'Soviet Union'), ('ES', 'Spain'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('TW', 'Taiwan'), ('TH', 'Thailand'), ('TR', 'Turkey'), ('UA', 'Ukraine'), ('GB', 'United Kingdom'), ('US', 'United States'), ('WG', 'West Germany'), ('YU', 'Yugoslavia')], max_length=2, null=True),
        ),
    ]
