# Generated by Django 5.1.5 on 2025-02-07 09:44

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_gender'),
        ('films', '0008_alter_filmsession_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsession',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='filmsession',
            index=models.Index(fields=['datetime'], name='films_films_datetim_79b24e_idx'),
        ),
        migrations.AddIndex(
            model_name='filmsession',
            index=models.Index(django.db.models.functions.datetime.ExtractHour('datetime'), name='idx_filmsession_hour'),
        ),
        migrations.AddIndex(
            model_name='filmsession',
            index=models.Index(django.db.models.functions.datetime.ExtractWeekDay('datetime'), name='idx_filmsession_weekday'),
        ),
        migrations.AddIndex(
            model_name='filmsession',
            index=models.Index(django.db.models.functions.datetime.ExtractWeekDay('datetime'), django.db.models.functions.datetime.ExtractHour('datetime'), name='idx_filmsession_day_hour'),
        ),
    ]
