# Generated by Django 5.1.5 on 2025-01-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_film_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='directors',
        ),
    ]
