# Generated by Django 5.1.5 on 2025-01-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_remove_film_directors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='id',
        ),
        migrations.AlterField(
            model_name='film',
            name='cc_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
