# Generated by Django 5.1.5 on 2025-01-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0002_alter_director_options'),
        ('films', '0011_remove_film_id_alter_film_cc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(related_name='films', to='directors.director'),
        ),
    ]
