INSERT INTO categories_category (number, title, year) VALUES (1, "Watch a film from the CC40 Boxset", 2025);
INSERT INTO categories_category (number, title, year, custom_criteria) VALUES (2, "Watch a film from the year you were born", 2025, '{"year": {"user": "date_of_birth"}}');
INSERT INTO categories_category (number, title, year) VALUES (3, "Directed by Robert Altman", 2025);
INSERT INTO categories_category (number, title, year) VALUES (4, "Watch a film that would be your first choice in the Criterion Closet", 2025);
INSERT INTO categories_category (number, title, year) VALUES (5, "Great Soundtracks", 2025);
INSERT INTO categories_category (number, title, year) VALUES (6, "John Turturro’s Adventures in Moviegoing", 2025);
INSERT INTO categories_category (number, title, year) VALUES (7, "1920s", 2025);
INSERT INTO categories_category (number, title, year) VALUES (8, "Watch a film that will be added to the physical collection in 2025", 2025);
INSERT INTO categories_category (number, title, year) VALUES (9, "1930s", 2025);
INSERT INTO categories_category (number, title, year) VALUES (10, "Andrew Garfield’s Closet Picks", 2025);
INSERT INTO categories_category (number, title, year) VALUES (11, "1940s", 2025);
INSERT INTO categories_category (number, title, year) VALUES (12, "Celine Song’s Top 10", 2025);
INSERT INTO categories_category (number, title, year) VALUES (13, "1950s", 2025);
INSERT INTO categories_category (number, title, year) VALUES (14, "Watch a film from the Criterion Channel’s all time favorites lists", 2025);
INSERT INTO categories_category (number, title, year) VALUES (15, "1960s", 2025);
INSERT INTO categories_category (number, title, year) VALUES (16, "Watch a film that is currently out of print from the physical collection", 2025);
INSERT INTO categories_category (number, title, year) VALUES (17, "1970s", 2025);
INSERT INTO categories_category (number, title, year) VALUES (18, "William Friedkin’s Closet Picks", 2025);
INSERT INTO categories_category (number, title, year) VALUES (19, "1980s", 2025);
INSERT INTO categories_category (number, title, year) VALUES (20, "Spine #451-499", 2025);
INSERT INTO categories_category (number, title, year) VALUES (21, "1990s", 2025);
INSERT INTO categories_category (number, title, year) VALUES (22, "Documentary", 2025);
INSERT INTO categories_category (number, title, year) VALUES (23, "2000s", 2025);
INSERT INTO categories_category (number, title, year) VALUES (24, "Janus Contemporaries", 2025);
INSERT INTO categories_category (number, title, year) VALUES (25, "2010s", 2025);
INSERT INTO categories_category (number, title, year) VALUES (26, "Bill Hader’s Second Closet Picks", 2025);
INSERT INTO categories_category (number, title, year) VALUES (27, "2020s", 2025);
INSERT INTO categories_category (number, title, year) VALUES (28, "Noir and Neonoir", 2025);
INSERT INTO categories_category (number, title, year) VALUES (29, "All Time Top Criterion Closet Picks", 2025);
INSERT INTO categories_category (number, title, year) VALUES (30, "Criterion Releases Never Picked in the Closet", 2025);
INSERT INTO categories_category (number, title, year) VALUES (31, "North American film", 2025);
INSERT INTO categories_category (number, title, year) VALUES (32, "Ayo Edebiri’s Closet Picks", 2025);
INSERT INTO categories_category (number, title, year) VALUES (33, "Wim Wenders’ Adventures in Moviegoing", 2025);
INSERT INTO categories_category (number, title, year) VALUES (34, "South American film", 2025);
INSERT INTO categories_category (number, title, year) VALUES (35, "Random Number Generator", 2025);
INSERT INTO categories_category (number, title, year) VALUES (36, "AAPI Filmmakers", 2025);
INSERT INTO categories_category (number, title, year) VALUES (37, "Watch a film shorter than 80 minutes", 2025);
INSERT INTO categories_category (number, title, year) VALUES (38, "European film", 2025);
INSERT INTO categories_category (number, title, year) VALUES (39, "Cult Movies", 2025);
INSERT INTO categories_category (number, title, year) VALUES (40, "Isabella Rossellini’s Adventures in Moviegoing", 2025);
INSERT INTO categories_category (number, title, year) VALUES (41, "Winona Ryder’s Closet Picks", 2025);
INSERT INTO categories_category (number, title, year) VALUES (42, "African film", 2025);
INSERT INTO categories_category (number, title, year) VALUES (43, "John Carpenter’s Top 10", 2025);
INSERT INTO categories_category (number, title, year) VALUES (44, "Horror", 2025);
INSERT INTO categories_category (number, title, year) VALUES (45, "Asian film", 2025);
INSERT INTO categories_category (number, title, year) VALUES (46, "Dark Comedies", 2025);
INSERT INTO categories_category (number, title, year) VALUES (47, "Rachel Kushner’s Adventures in Moviegoing", 2025);
INSERT INTO categories_category (number, title, year) VALUES (48, "Australian film", 2025);
INSERT INTO categories_category (number, title, year) VALUES (49, "Female Filmmakers", 2025);
INSERT INTO categories_category (number, title, year) VALUES (50, "Ben Wheatley’s Closet Picks", 2025);
INSERT INTO categories_category (number, title, year) VALUES (51, "A film by a director whose work you have not seen before", 2025);
INSERT INTO categories_category (number, title, year) VALUES (52, "Watch any Criterion film from your watchlist", 2025);