# Generated by Django 5.1.5 on 2025-02-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'User Preference'},
        ),
    ]
