# Generated by Django 5.1.5 on 2025-02-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userpreference_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='session_times',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
