# Generated by Django 5.1.5 on 2025-02-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreference_session_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='filter_not_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='filter_watchlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='filter_with_sessions',
            field=models.BooleanField(default=False),
        ),
    ]
