databases:
  - name: criterionchallengedb
    plan: free
    databaseName: criterionchallenge
    user: criterionchallenge

services:
  - type: web
    plan: free
    name: criterionchallenge
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn criterionchallenge.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: criterionchallengedb
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4