# Generated by Django 5.1.5 on 2025-01-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
    ]
