INSERT INTO common_country (code, name) VALUES ('AO', 'Angola');
INSERT INTO common_country (code, name) VALUES ('AR', 'Argentina');
INSERT INTO common_country (code, name) VALUES ('AU', 'Australia');
INSERT INTO common_country (code, name) VALUES ('AT', 'Austria');
INSERT INTO common_country (code, name) VALUES ('BD', 'Bangladesh');
INSERT INTO common_country (code, name) VALUES ('BE', 'Belgium');
INSERT INTO common_country (code, name) VALUES ('BR', 'Brazil');
INSERT INTO common_country (code, name) VALUES ('CM', 'Cameroon');
INSERT INTO common_country (code, name) VALUES ('CA', 'Canada');
INSERT INTO common_country (code, name) VALUES ('CN', 'China');
INSERT INTO common_country (code, name) VALUES ('CU', 'Cuba');
INSERT INTO common_country (code, name) VALUES ('CZ', 'Czechoslovakia');
INSERT INTO common_country (code, name) VALUES ('DK', 'Denmark');
INSERT INTO common_country (code, name) VALUES ('ET', 'Ethiopia');
INSERT INTO common_country (code, name) VALUES ('FI', 'Finland');
INSERT INTO common_country (code, name) VALUES ('FR', 'France');
INSERT INTO common_country (code, name) VALUES ('DE', 'Germany');
INSERT INTO common_country (code, name) VALUES ('GR', 'Greece');
INSERT INTO common_country (code, name) VALUES ('GT', 'Guatemala');
INSERT INTO common_country (code, name) VALUES ('HK', 'Hong Kong');
INSERT INTO common_country (code, name) VALUES ('HU', 'Hungary');
INSERT INTO common_country (code, name) VALUES ('IS', 'Iceland');
INSERT INTO common_country (code, name) VALUES ('IN', 'India');
INSERT INTO common_country (code, name) VALUES ('ID', 'Indonesia');
INSERT INTO common_country (code, name) VALUES ('IR', 'Iran');
INSERT INTO common_country (code, name) VALUES ('IE', 'Ireland');
INSERT INTO common_country (code, name) VALUES ('IT', 'Italy');
INSERT INTO common_country (code, name) VALUES ('JP', 'Japan');
INSERT INTO common_country (code, name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO common_country (code, name) VALUES ('LS', 'Lesotho');
INSERT INTO common_country (code, name) VALUES ('MX', 'Mexico');
INSERT INTO common_country (code, name) VALUES ('MA', 'Morocco');
INSERT INTO common_country (code, name) VALUES ('NZ', 'New Zealand');
INSERT INTO common_country (code, name) VALUES ('NG', 'Nigeria');
INSERT INTO common_country (code, name) VALUES ('NO', 'Norway');
INSERT INTO common_country (code, name) VALUES ('PH', 'Philippines');
INSERT INTO common_country (code, name) VALUES ('PL', 'Poland');
INSERT INTO common_country (code, name) VALUES ('PT', 'Portugal');
INSERT INTO common_country (code, name) VALUES ('MK', 'Republic of Macedonia');
INSERT INTO common_country (code, name) VALUES ('RO', 'Romania');
INSERT INTO common_country (code, name) VALUES ('SN', 'Senegal');
INSERT INTO common_country (code, name) VALUES ('KR', 'South Korea');
INSERT INTO common_country (code, name) VALUES ('SU', 'Soviet Union');
INSERT INTO common_country (code, name) VALUES ('ES', 'Spain');
INSERT INTO common_country (code, name) VALUES ('SE', 'Sweden');
INSERT INTO common_country (code, name) VALUES ('CH', 'Switzerland');
INSERT INTO common_country (code, name) VALUES ('TW', 'Taiwan');
INSERT INTO common_country (code, name) VALUES ('TH', 'Thailand');
INSERT INTO common_country (code, name) VALUES ('TR', 'Turkey');
INSERT INTO common_country (code, name) VALUES ('UA', 'Ukraine');
INSERT INTO common_country (code, name) VALUES ('GB', 'United Kingdom');
INSERT INTO common_country (code, name) VALUES ('US', 'United States');
INSERT INTO common_country (code, name) VALUES ('WG', 'West Germany');
INSERT INTO common_country (code, name) VALUES ('YU', 'Yugoslavia');
