# Generated by Django 5.1.5 on 2025-01-17 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Enter a number between 1 and 52.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("year", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ("films", models.ManyToManyField(related_name="categories", to="films.film")),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["number"],
                "unique_together": {("number", "year")},
            },
        ),
    ]
