# Generated by Django 5.1.5 on 2025-01-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmcategory',
            options={'verbose_name': 'film-category relation', 'verbose_name_plural': 'film-category relations'},
        ),
    ]
