# Generated by Django 5.1.5 on 2025-01-17 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('number', 'year')},
        ),
    ]
