# Generated by Django 5.1.5 on 2025-01-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_filmcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='films',
        ),
        migrations.DeleteModel(
            name='FilmCategory',
        ),
    ]
