# Generated by Django 5.1.5 on 2025-01-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_remove_category_films'),
        ('films', '0011_remove_film_id_alter_film_cc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='films',
            field=models.ManyToManyField(related_name='categories', to='films.film'),
        ),
    ]
