# Generated by Django 5.1.5 on 2025-01-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['name']},
        ),
    ]
