# Generated by Django 5.1.5 on 2025-01-27 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_gender'),
        ('directors', '0002_director_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='common.gender'),
        ),
    ]
