# Generated by Django 5.1.5 on 2025-01-24 20:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('locked', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='categories.category')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='films.film')),
            ],
            options={
                'ordering': ['category__number'],
            },
        ),
    ]
