# Generated by Django 5.1.5 on 2025-01-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='watched',
            new_name='locked',
        ),
    ]
