# Generated by Django 5.1.5 on 2025-01-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pick',
            options={'ordering': ['category__number']},
        ),
    ]
