# Generated by Django 5.1.5 on 2025-01-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_alter_pick_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pick',
            name='unique_user_year_film',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='film',
        ),
    ]
